# Generated by Django 2.2.4 on 2020-09-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titlelinkonly',
            name='content',
        ),
        migrations.AddField(
            model_name='titlelinkonly',
            name='link',
            field=models.URLField(default='example_link'),
            preserve_default=False,
        ),
    ]
