# Generated by Django 3.1.1 on 2021-01-13 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='bez tytulu', max_length=250)),
                ('date_of_publication', models.DateTimeField(auto_now_add=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='uploads/')),
                ('slug', models.SlugField(max_length=250, unique_for_date='date_of_publication')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
