# Generated by Django 3.1.1 on 2021-01-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
