# Generated by Django 2.2.4 on 2020-09-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200902_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlelinkonly',
            name='title',
            field=models.CharField(max_length=250, unique_for_month=True),
        ),
    ]
