# Generated by Django 2.2.4 on 2020-09-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200903_1917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TitleLinkOnly',
            new_name='Olawa24_news',
        ),
    ]
