# Generated by Django 3.1.1 on 2021-01-23 10:05

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='uploads/'),
        ),
    ]
