# Generated by Django 2.2.4 on 2020-09-04 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200903_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_of_publication',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
