# Generated by Django 2.2.4 on 2020-09-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_news_date_of_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique_for_month=True)),
                ('link', models.URLField()),
                ('which_site', models.CharField(choices=[('kino_odra', 'Kino Odra'), ('gokino', 'GO!Kino')], default='kino_odra', max_length=10)),
                ('duration', models.IntegerField()),
                ('time_of_spectacle', models.DateTimeField()),
            ],
        ),
    ]
