# Generated by Django 2.2.4 on 2020-09-05 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_one_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Movie')),
            ],
        ),
    ]
