# Generated by Django 2.2.4 on 2020-09-06 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_movie_one_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='time_of_spectacle',
        ),
        migrations.AlterField(
            model_name='movie_one_date',
            name='movie_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_spectacles', to='homepage.Movie'),
        ),
    ]
