# Generated by Django 3.1.1 on 2020-09-08 07:45

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_simplead_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplead',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
