# Generated by Django 3.1.1 on 2020-09-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20200908_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplead',
            name='slug',
            field=models.SlugField(default='test', max_length=250, unique_for_date=models.DateTimeField(auto_now_add=True)),
            preserve_default=False,
        ),
    ]
