# Generated by Django 3.1.1 on 2020-09-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_simplead_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplead',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=250, unique_for_date=models.DateTimeField(auto_now_add=True)),
        ),
    ]
