# Generated by Django 3.1.1 on 2020-09-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_auto_20200909_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplead',
            name='price',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
