# Generated by Django 3.1.1 on 2020-09-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_simplead_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplead',
            name='price',
            field=models.IntegerField(),
        ),
    ]
