# Generated by Django 3.1.1 on 2020-09-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_auto_20200910_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='which_site',
            field=models.CharField(choices=[('olawa24', 'Oława24'), ('tuolawa', 'TuOława'), ('umolawa', 'UMOława')], default='tuolawa', max_length=10),
        ),
    ]
