# Generated by Django 3.1.1 on 2020-09-11 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20200911_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='day_of_spectacle',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
