# Generated by Django 3.1.1 on 2020-09-14 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0022_forumresponse_forumtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtopic',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='date_of_publication'),
        ),
        migrations.AlterField(
            model_name='simplead',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='simplead',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='date_of_publication'),
        ),
    ]
