# Generated by Django 3.1.1 on 2020-09-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_auto_20200914_2018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_one_date',
            new_name='MovieSpectacles',
        ),
    ]
