# Generated by Django 3.1.1 on 2021-01-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_kinoodramoviesmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KinoOdraMoviesManager',
        ),
    ]
